[#6][Chore] Configure Unit Tests
malparty/react-survey pull request #35
Opened 2021-10-15 02:35 UTC by malparty

- #6 

## What happened 👀

- Add a GitHub action 'jest' to run unit tests on every `push` (any branch)
- Add missing unit tests 
- Add code coverage information in PR

## Insight 📝

`N/A`

## Proof Of Work 📹

WIP

2021-10-17 18:03 UTC, rafayet-monon reviewed
@malparty As per the preferred requirement, should we try using `react-testing-library`?

![image](https://user-images.githubusercontent.com/14927672/137639351-68324a59-5289-42e0-972e-bf924b7de0d7.png)

2021-10-18 04:35 UTC, malparty commented
> @malparty As per the preferred requirement, should we try using `react-testing-library`?
> 
> ![image](https://user-images.githubusercontent.com/14927672/137639351-68324a59-5289-42e0-972e-bf924b7de0d7.png)

Woups! I got misleading by the training :P 
![image](https://user-images.githubusercontent.com/77609814/137669831-1ad35472-7f86-4324-a874-203208fb892f.png)

--> Small note added to the training path (pending on Olivier confirmation). I will rework these tests today.

The PR is back as DRAFT until this change will be done. Thanks @rafayet-monon for pointing that out! :)

**Update:** Enzyme removed and fully replaced by `react-testing-library` tests. ✅

2021-10-19 11:56 UTC, carryall requested changes

2021-10-19 11:56 UTC, carryall commented on .github/workflows/test-coverage.yml
> +      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
Regarding [the convention](https://nimblehq.co/compass/development/code-conventions/github-actions/), should we add some spaces here? 

```suggestion
name: 'coverage'

on: push

jobs:
  coverage:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v1

      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
```

2021-10-19 11:56 UTC, carryall commented on .github/workflows/test-coverage.yml
> +      - uses: actions/checkout@v1
Should we also add names for these steps?
```suggestion
      - name: Checkout
        uses: actions/checkout@v1
```

2021-10-19 11:56 UTC, carryall commented on .github/workflows/test-coverage.yml
> +name: 'coverage'
Can we remove the `'` here? and maybe rename it to `Test Coverage`
```suggestion
name: Test Coverage
```

2021-10-19 11:56 UTC, carryall commented on .github/workflows/test.yml
> +      run: yarn test
```suggestion
name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Install modules
      run: yarn

    - name: Run tests
      run: yarn test
```

2021-10-19 11:56 UTC, carryall commented on src/App.test.tsx
> +describe('<App />', () => {
How about just `App`?
```suggestion
describe('App', () => {
```

2021-10-19 11:56 UTC, carryall commented on src/tests/Login/index.test.tsx
> +describe('<LoginScreen />', () => {
How about just `LoginScreen`?
```suggestion
describe('LoginScreen', () => {
```

2021-10-19 11:56 UTC, carryall commented on src/tests/Login/index.test.tsx
> +    const screenClass = 'login-screen';
How about moving this a `const` so we can reuse it in the next test case?

2021-10-19 11:56 UTC, carryall commented on src/tests/components/BackgroundImage/index.test.tsx
> +describe('<BackgroundImage />', () => {
```suggestion
describe('BackgroundImage', () => {
```

2021-10-19 11:56 UTC, carryall commented on src/tests/components/BackgroundImage/index.test.tsx
> +    expect(backgroundImage.getAllByTestId('background-image')).toHaveLength(1);
How about moving the test id to a `const` too?

2021-10-20 03:13 UTC, malparty commented on .github/workflows/test.yml
> +      run: yarn test
✅ 👌 6c62991

2021-10-20 03:13 UTC, malparty commented on .github/workflows/test-coverage.yml
> +name: 'coverage'
✅ 👌 6c62991

2021-10-20 03:13 UTC, malparty commented on .github/workflows/test-coverage.yml
> +      - uses: actions/checkout@v1
✅ 👌 80a0b46

2021-10-20 03:14 UTC, malparty commented on .github/workflows/test-coverage.yml
> +      - uses: artiomtr/jest-coverage-report-action@v2.0-rc.5
✅ 👌 6c62991

2021-10-20 03:15 UTC, malparty commented on src/App.test.tsx
> +describe('<App />', () => {
I saw that in some training and I kind of liked the message it carries: "describe the App component" (while `describe('App')` carries a less clear message "describe the App" — the whole application?).

But it does not change much to let's go for `App` alone ;-)

2021-10-20 03:21 UTC, malparty commented on src/tests/Login/index.test.tsx
> +    const screenClass = 'login-screen';
✅ Done in 39a594b :)

2021-10-20 03:21 UTC, malparty commented on src/tests/Login/index.test.tsx
> +describe('<LoginScreen />', () => {
✅ Done in 39a594b :)

2021-10-20 03:21 UTC, malparty commented on src/App.test.tsx
> +describe('<App />', () => {
✅ Done in 39a594b :)

2021-10-20 03:21 UTC, malparty commented on src/tests/components/BackgroundImage/index.test.tsx
> +describe('<BackgroundImage />', () => {
✅ Done in 39a594b :)

2021-10-20 03:22 UTC, malparty commented on src/tests/components/BackgroundImage/index.test.tsx
> +    expect(backgroundImage.getAllByTestId('background-image')).toHaveLength(1);
✅ Done in 39a594b :)

2021-10-20 11:41 UTC, rafayet-monon commented on src/components/BackgroundImage/index.tsx
> +        <img className="background-image__img" src={defaultImage} role="presentation" alt="" data-testid="background-image" />
Just a suggestion, you can change the `data-testid` to be a different name as well. I would suggest to use `data-test-id` and maybe use it in both unit and cypress tests.

2021-10-21 04:53 UTC, malparty commented on src/components/BackgroundImage/index.tsx
> +        <img className="background-image__img" src={defaultImage} role="presentation" alt="" data-testid="background-image" />
Thanks, good tips :)
✅ Done in 1b581d3 for Jest. I will check in the Cypress PR to configure it there.

2021-10-22 03:23 UTC, carryall commented on src/tests/components/BackgroundImage/index.test.tsx
> +import {render} from '@testing-library/react'
```suggestion
import { render } from '@testing-library/react'
```

2021-10-22 03:23 UTC, carryall commented on src/tests/Login/index.test.tsx
> +import LoginScreen from '../../screens/Login';
I'm not sure but can we use the alias path import here?

2021-10-25 03:33 UTC, malparty commented on src/tests/components/BackgroundImage/index.test.tsx
> +import {render} from '@testing-library/react'
✅ Fixed in 6c2ad07 :)

2021-10-25 03:34 UTC, malparty commented on src/tests/Login/index.test.tsx
> +import LoginScreen from '../../screens/Login';
Yes we can~ 
That made me realized I forgot to configure the tsconfig.json so that VS Code can auto-complete this imports~ (and so auto-import using aliases :3)

✅ Done in 6c2ad07

2021-10-25 03:53 UTC, carryall approved these changes

2021-10-26 05:06 UTC, rafayet-monon approved these changes

2021-10-26 06:34 UTC, merged